'use client';

import { useState, useEffect } from 'react';
import { Play, Pause, FastForward, Rewind, Volume2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Slider } from '@/components/ui/slider';

export function AudioOverview() {
    const [isPlaying, setIsPlaying] = useState(false);
    const [progress, setProgress] = useState(0);

    // Mock progress simulation
    useEffect(() => {
        let interval: NodeJS.Timeout;
        if (isPlaying) {
            interval = setInterval(() => {
                setProgress((prev) => (prev >= 100 ? 0 : prev + 0.5));
            }, 100);
        }
        return () => clearInterval(interval);
    }, [isPlaying]);

    const formatTime = (value: number) => {
        const totalSeconds = (value / 100) * 180; // Mock 3 min duration
        const minutes = Math.floor(totalSeconds / 60);
        const seconds = Math.floor(totalSeconds % 60);
        return `${minutes}:${seconds.toString().padStart(2, '0')}`;
    };

    return (
        <div className="flex flex-col items-center justify-center p-8 space-y-8 animate-in fade-in duration-500">
            <div className="text-center space-y-2">
                <h2 className="text-2xl font-bold text-gray-900 tracking-tight">Audio Overview</h2>
                <p className="text-gray-500">Deep dive into your sources with AI-generated hosts.</p>
            </div>

            {/* Visualizer */}
            <div className="flex items-center justify-center gap-1 h-24 w-full max-w-md">
                {Array.from({ length: 20 }).map((_, i) => (
                    <div
                        key={i}
                        className={`w-2 bg-blue-500 rounded-full transition-all duration-300 ${isPlaying ? 'animate-pulse' : 'h-2 opacity-30'
                            }`}
                        style={{
                            height: isPlaying ? `${40 + (i % 5) * 10}%` : '8px',
                            opacity: isPlaying ? 1 : 0.3,
                        }}
                    />
                ))}
            </div>

            {/* Controls */}
            <Card className="p-6 w-full max-w-md bg-white shadow-lg border-gray-100 rounded-2xl">
                <div className="space-y-6">
                    {/* Progress */}
                    <div className="space-y-2">
                        <Slider value={[progress]} max={100} step={1} className="cursor-pointer" />
                        <div className="flex justify-between text-xs text-gray-400 font-medium">
                            <span>{formatTime(progress)}</span>
                            <span>3:00</span>
                        </div>
                    </div>

                    {/* Buttons */}
                    <div className="flex items-center justify-center gap-6">
                        <Button variant="ghost" size="icon" className="text-gray-400 hover:text-gray-900">
                            <Rewind className="h-6 w-6" />
                        </Button>

                        <button
                            onClick={() => setIsPlaying(!isPlaying)}
                            className="w-16 h-16 flex items-center justify-center bg-gray-900 text-white rounded-full hover:scale-105 transition-transform shadow-xl"
                        >
                            {isPlaying ? (
                                <Pause className="h-6 w-6 fill-current" />
                            ) : (
                                <Play className="h-6 w-6 fill-current ml-1" />
                            )}
                        </button>

                        <Button variant="ghost" size="icon" className="text-gray-400 hover:text-gray-900">
                            <FastForward className="h-6 w-6" />
                        </Button>
                    </div>
                </div>
            </Card>

            <p className="text-xs text-gray-400 flex items-center gap-2">
                <Volume2 className="h-3 w-3" />
                Generated by Notebook AI
            </p>
        </div>
    );
}
